//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ComfyUIWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComfyUIWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ComfyUIWeb", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_Cancel {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_Clear {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_OK {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今天.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_Today {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        internal static string ASPxEditorsStringId_DefaultErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DefaultErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;enter a value&amp;gt;.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterConrol_EmptyEnter {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterConrol_EmptyEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Condition.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddCondition {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new condition to this group.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddConditionHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddConditionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddGroup {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new item to the list.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddValueHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_BetweenAnd {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_BetweenAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_Cancel {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals,Does not equal,Is greater than,Is greater than or equal to,Is less than,Is less than or equal to,Is between,Is not between,Contains,Does not contain,Begins with,Ends with,Is like,Is not like,Is blank,Is not blank,Is any of,Is none of.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_ClauseType {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_ClauseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_ClearFilter {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  And,Or,Not And,Not Or.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_GroupType {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_GroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_OK {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Builder.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_PopupHeaderText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_PopupHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_Remove {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes this condition.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_RemoveConditionHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_RemoveConditionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Filter.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_ShowFilterControl {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_ShowFilterControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression validation failed.
        /// </summary>
        internal static string ASPxEditorsStringId_RegExValidationErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.RegExValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string ASPxEditorsStringId_RequiredFieldErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.RequiredFieldErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Collapse].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_Collapse {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_DragAndDropHideColumnIcon {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_DragAndDropHideColumnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Expand].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_Expand {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Condition].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_FilterRowButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_FilterRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Filter].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_HeaderFilterButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_HeaderFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Filtered].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_HeaderFilterButtonActive {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_HeaderFilterButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ascending).
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_SortedAscending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Descending).
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_SortedDescending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins with.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterBeginsWith {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterContains {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterEndsWith {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterEquals {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterGreater {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than or equal to.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterGreaterOrEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLess {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than or equal to.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLessOrEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t equal.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterNotEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        internal static string ASPxGridViewStringId_Checked {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandCancel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandClearFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandDelete {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編輯.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandEdit {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandNew {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選擇.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandSelect {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandUpdate {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存後關閉.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandUpdateExit {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandUpdateExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定要刪除當前行嗎?.
        /// </summary>
        internal static string ASPxGridViewStringId_ConfirmDelete {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Chooser.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationWindowCaption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 當前沒有數據可以顯示.
        /// </summary>
        internal static string ASPxGridViewStringId_EmptyDataRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.EmptyDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column here....
        /// </summary>
        internal static string ASPxGridViewStringId_EmptyHeaders {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.EmptyHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (下一頁繼續).
        /// </summary>
        internal static string ASPxGridViewStringId_GroupContinuedOnNextPage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.GroupContinuedOnNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header here to group by that column.
        /// </summary>
        internal static string ASPxGridViewStringId_GroupPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.GroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowAllItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowAllItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Form.
        /// </summary>
        internal static string ASPxGridViewStringId_PopupEditFormCaption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.PopupEditFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked.
        /// </summary>
        internal static string ASPxGridViewStringId_Unchecked {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constrain Proportions On.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_Alt_ConstrainProportions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.Alt_ConstrainProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constrain Proportions Off.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_Alt_ConstrainProportionsOff {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.Alt_ConstrainProportionsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonCancel {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonChange {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonInsert {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonOk {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更換圖片.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ChangeImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更換聯接.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ChangeLink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ChangeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 應用樣式.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandApplyCss {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandApplyCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景色.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandBackColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加粗.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandBold {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 項列表.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandBulletList {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandBulletList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中間對齊.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCenter {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拼寫檢查.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCheckSpelling {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCheckSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 復制.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCopy {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCut {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前景色.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandForeColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩进.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandIndent {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ]斜体.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandItalic {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandJustify {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左對齊.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandLeft {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered List.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandOrderedList {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdent.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandOutdent {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandOutdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘貼.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandPaste {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from Word.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandPasteRtf {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandPasteRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandPrint {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重做.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandRedo {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Format.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandRemoveFormat {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandRemoveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右對齊.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandRight {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandStrikethrough {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandStrikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandSubscript {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandSubscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandSuperscript {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandSuperscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下劃線.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandUnderline {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤消.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandUndo {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除聯接.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandUnlink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandUnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DesignViewTab {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DesignViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Name.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_FontName {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_FontSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_HtmlViewTab {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.HtmlViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create thumbnail.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_CreateThumbnail {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_CreateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom size.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_CustomSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_CustomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Description {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Height {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New image name.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_NewImageName {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_NewImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original image size.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_OriginalSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pixels.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Pixels {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Position {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_PositionCenter {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_PositionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-aligned.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_PositionLeft {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_PositionLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-aligned.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_PositionRight {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_PositionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尺寸.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Size {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 寬度.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Width {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入圖片.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter image web address.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_EnterUrl {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_EnterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 從本地文件.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_FromLocal {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_FromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 從網絡文件 (URL).
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_FromWeb {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_FromWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多選項.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_MoreOptions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 圖片預覽.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_Preview {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file to this server.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_SaveToServer {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_SaveToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse your computer for the image file to upload.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_UploadInstructions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_UploadInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入聯接.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Properties.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_DisplayProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_DisplayProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Email {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail to.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_EmailTo {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_EmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new window.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_OpenInNewWindow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 標題.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Subject {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Text {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Url {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_Paragraph {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste inside the following box and hit OK..
        /// </summary>
        internal static string ASPxHtmlEditorStringId_PasteRtf_Instructions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.PasteRtf_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strip font family.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_PasteRtf_StripFont {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.PasteRtf_StripFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 預覽.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_PreviewTab {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.PreviewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能為空.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_RequiredFieldError {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全選.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SelectAll {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Dictionary.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_AddToDictionaryButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.AddToDictionaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_CancelButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change All.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChangeAllButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChangeAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChangeButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change To:.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChangeTo {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChangeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which dictionary to use when checking your spelling..
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChooseDictionary {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChooseDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_CloseButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spelling check is complete..
        /// </summary>
        internal static string ASPxSpellCheckerStringId_FinishSpellChecking {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.FinishSpellChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General options.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_GeneralOptions {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.GeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore All.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreAllButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore e-mails.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreEmails {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore words in MiXeDcAsE.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreMixedCase {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreMixedCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore words with numbers.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreNumbers {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Once.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreOnceButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreOnceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore markup tags.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreTags {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore words in UPPERCASE.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreUppercase {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore URLs.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreUrls {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International dictionaries.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_InternationalDictionaries {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.InternationalDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_Language {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Suggestions).
        /// </summary>
        internal static string ASPxSpellCheckerStringId_NoSuggestionsText {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.NoSuggestionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in Dictionary:.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_NotInDictionary {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.NotInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_OkButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        internal static string ASPxSpellCheckerStringId_OptionsButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.OptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling Options.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_OptionsFormCaption {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.OptionsFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Spelling.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_SpellCheckFormCaption {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.SpellCheckFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Collapse].
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_Collapse {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_DragAndDropHideColumnIcon {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_DragAndDropHideColumnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Expand].
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_Expand {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ascending).
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_SortedAscending {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Descending).
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_SortedDescending {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandCancel {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandDelete {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編輯.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandEdit {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandNew {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandUpdate {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定要刪除當前行嗎?.
        /// </summary>
        internal static string ASPxTreeListStringId_ConfirmDelete {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Chooser.
        /// </summary>
        internal static string ASPxTreeListStringId_CustomizationWindowCaption {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CustomizationWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node has descendant nodes..
        /// </summary>
        internal static string ASPxTreeListStringId_RecursiveDeleteError {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.RecursiveDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages.
        /// </summary>
        internal static string ASPxWebStringId_DataView_PagerSummaryAllPages {
            get {
                return ResourceManager.GetString("ASPxWebStringId.DataView_PagerSummaryAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string ASPxWebStringId_DataView_PagerSummaryFormat {
            get {
                return ResourceManager.GetString("ASPxWebStringId.DataView_PagerSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加載中&amp;hellip;  .
        /// </summary>
        internal static string ASPxWebStringId_Loading {
            get {
                return ResourceManager.GetString("ASPxWebStringId.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to top.
        /// </summary>
        internal static string ASPxWebStringId_NewsControl_BackToTop {
            get {
                return ResourceManager.GetString("ASPxWebStringId.NewsControl_BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        internal static string ASPxWebStringId_NewsControl_Page {
            get {
                return ResourceManager.GetString("ASPxWebStringId.NewsControl_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有頁.
        /// </summary>
        internal static string ASPxWebStringId_Pager_All {
            get {
                return ResourceManager.GetString("ASPxWebStringId.Pager_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一頁.
        /// </summary>
        internal static string ASPxWebStringId_Pager_First {
            get {
                return ResourceManager.GetString("ASPxWebStringId.Pager_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最後一頁.
        /// </summary>
        internal static string ASPxWebStringId_Pager_Last {
            get {
                return ResourceManager.GetString("ASPxWebStringId.Pager_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一頁.
        /// </summary>
        internal static string ASPxWebStringId_Pager_Next {
            get {
                return ResourceManager.GetString("ASPxWebStringId.Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前一頁.
        /// </summary>
        internal static string ASPxWebStringId_Pager_Prev {
            get {
                return ResourceManager.GetString("ASPxWebStringId.Pager_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第 {0} 頁 共 {1} 頁 (共 {2} 條記錄).
        /// </summary>
        internal static string ASPxWebStringId_Pager_SummaryAllPagesFormat {
            get {
                return ResourceManager.GetString("ASPxWebStringId.Pager_SummaryAllPagesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第 {0} 頁 共 {1} 頁 (共 {2} 條記錄).
        /// </summary>
        internal static string ASPxWebStringId_Pager_SummaryFormat {
            get {
                return ResourceManager.GetString("ASPxWebStringId.Pager_SummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Close].
        /// </summary>
        internal static string ASPxWebStringId_PopupControl_CloseButton {
            get {
                return ResourceManager.GetString("ASPxWebStringId.PopupControl_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Resize].
        /// </summary>
        internal static string ASPxWebStringId_PopupControl_SizeGrip {
            get {
                return ResourceManager.GetString("ASPxWebStringId.PopupControl_SizeGrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Back to Top].
        /// </summary>
        internal static string ASPxWebStringId_TitleIndex_BackToTop {
            get {
                return ResourceManager.GetString("ASPxWebStringId.TitleIndex_BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:&amp;nbsp;&amp;nbsp;&amp;nbsp;.
        /// </summary>
        internal static string ASPxWebStringId_TitleIndex_FilterCaption {
            get {
                return ResourceManager.GetString("ASPxWebStringId.TitleIndex_FilterCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;?&lt;/b&gt; = any single character
        ///&lt;b&gt;*&lt;/b&gt; = any characters.
        /// </summary>
        internal static string ASPxWebStringId_TitleIndex_FilterHint {
            get {
                return ResourceManager.GetString("ASPxWebStringId.TitleIndex_FilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for this filter criteria.
        /// </summary>
        internal static string ASPxWebStringId_TitleIndex_NoData {
            get {
                return ResourceManager.GetString("ASPxWebStringId.TitleIndex_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ASPxWebStringId_UploadControl_AddButton {
            get {
                return ResourceManager.GetString("ASPxWebStringId.UploadControl_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string ASPxWebStringId_UploadControl_RemoveButton {
            get {
                return ResourceManager.GetString("ASPxWebStringId.UploadControl_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string ASPxWebStringId_UploadControl_UploadButton {
            get {
                return ResourceManager.GetString("ASPxWebStringId.UploadControl_UploadButton", resourceCulture);
            }
        }
    }
}
