//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MainRes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 Copyright © Esquel All Rights Reserved(2014) 的本地化字符串。
        /// </summary>
        internal static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 幫助 的本地化字符串。
        /// </summary>
        internal static string AppHelp {
            get {
                return ResourceManager.GetString("AppHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Help/zh-TW/index.htm 的本地化字符串。
        /// </summary>
        internal static string AppHelpPage {
            get {
                return ResourceManager.GetString("AppHelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 First Page 的本地化字符串。
        /// </summary>
        internal static string AppHome {
            get {
                return ResourceManager.GetString("AppHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 http://10.184.101.8/PMS_WebSite/main.aspx 的本地化字符串。
        /// </summary>
        internal static string AppLogoLink {
            get {
                return ResourceManager.GetString("AppLogoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Quality Code 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 MES Framework 的本地化字符串。
        /// </summary>
        internal static string AppNameEn {
            get {
                return ResourceManager.GetString("AppNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Version: 的本地化字符串。
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 關閉 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 關閉其它頁面 的本地化字符串。
        /// </summary>
        internal static string CloseOtherTabs {
            get {
                return ResourceManager.GetString("CloseOtherTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 關閉此頁面 的本地化字符串。
        /// </summary>
        internal static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 確定要刪除當前行嗎? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 確定刪除勾選的所有數據? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteSelected {
            get {
                return ResourceManager.GetString("ConfirmDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 確定要保存修改嗎? 的本地化字符串。
        /// </summary>
        internal static string ConfirmUpdate {
            get {
                return ResourceManager.GetString("ConfirmUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 無效。 的本地化字符串。
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 沒有勾選任何數據行。 的本地化字符串。
        /// </summary>
        internal static string NoSelectedData {
            get {
                return ResourceManager.GetString("NoSelectedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存成功。 的本地化字符串。
        /// </summary>
        internal static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
    }
}
