//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TitleRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitleRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TitleRes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 類別設置.
        /// </summary>
        internal static string AppCategory {
            get {
                return ResourceManager.GetString("AppCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表格設置.
        /// </summary>
        internal static string AppGridCustomize {
            get {
                return ResourceManager.GetString("AppGridCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 組別設置.
        /// </summary>
        internal static string AppGroup {
            get {
                return ResourceManager.GetString("AppGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导航设置.
        /// </summary>
        internal static string AppNavigation {
            get {
                return ResourceManager.GetString("AppNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告管理.
        /// </summary>
        internal static string AppNotice {
            get {
                return ResourceManager.GetString("AppNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色设置.
        /// </summary>
        internal static string AppRole {
            get {
                return ResourceManager.GetString("AppRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系統管理.
        /// </summary>
        internal static string AppSetting {
            get {
                return ResourceManager.GetString("AppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用戶管理.
        /// </summary>
        internal static string AppUser {
            get {
                return ResourceManager.GetString("AppUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本资料.
        /// </summary>
        internal static string BaseData {
            get {
                return ResourceManager.GetString("BaseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的最愛.
        /// </summary>
        internal static string UserFavorite {
            get {
                return ResourceManager.GetString("UserFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 個人信息.
        /// </summary>
        internal static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
    }
}
