//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserControlRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserControlRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UserControlRes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每頁顯示 {0} 條記錄.
        /// </summary>
        internal static string Pager_PageSizeFormat {
            get {
                return ResourceManager.GetString("Pager_PageSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第 {0} 頁 共 {1} 頁 (共 {2} 條記錄).
        /// </summary>
        internal static string Pager_PageSummaryFormat {
            get {
                return ResourceManager.GetString("Pager_PageSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 導航顯示.
        /// </summary>
        internal static string Role_NavForRole {
            get {
                return ResourceManager.GetString("Role_NavForRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 權限.
        /// </summary>
        internal static string Role_Permission {
            get {
                return ResourceManager.GetString("Role_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有.
        /// </summary>
        internal static string Role_SelectAll {
            get {
                return ResourceManager.GetString("Role_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選擇.
        /// </summary>
        internal static string ToolBar_Accept {
            get {
                return ResourceManager.GetString("ToolBar_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選擇當前數據.
        /// </summary>
        internal static string ToolBar_AcceptToolTip {
            get {
                return ResourceManager.GetString("ToolBar_AcceptToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        internal static string ToolBar_Clear {
            get {
                return ResourceManager.GetString("ToolBar_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空查詢條件.
        /// </summary>
        internal static string ToolBar_ClearToolTip {
            get {
                return ResourceManager.GetString("ToolBar_ClearToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除.
        /// </summary>
        internal static string ToolBar_Delete {
            get {
                return ResourceManager.GetString("ToolBar_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除勾選的資料行.
        /// </summary>
        internal static string ToolBar_DeleteToolTip {
            get {
                return ResourceManager.GetString("ToolBar_DeleteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編輯.
        /// </summary>
        internal static string ToolBar_Edit {
            get {
                return ResourceManager.GetString("ToolBar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編輯當前數據行.
        /// </summary>
        internal static string ToolBar_EditToolTip {
            get {
                return ResourceManager.GetString("ToolBar_EditToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 導出.
        /// </summary>
        internal static string ToolBar_Export {
            get {
                return ResourceManager.GetString("ToolBar_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 導出報表.
        /// </summary>
        internal static string ToolBar_ExportToolTip {
            get {
                return ResourceManager.GetString("ToolBar_ExportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string ToolBar_GridCustomize {
            get {
                return ResourceManager.GetString("ToolBar_GridCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表格屬性设置.
        /// </summary>
        internal static string ToolBar_GridCustomizeToolTip {
            get {
                return ResourceManager.GetString("ToolBar_GridCustomizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幫助.
        /// </summary>
        internal static string ToolBar_Help {
            get {
                return ResourceManager.GetString("ToolBar_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顯示帮助.
        /// </summary>
        internal static string ToolBar_HelpTooltip {
            get {
                return ResourceManager.GetString("ToolBar_HelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 導入.
        /// </summary>
        internal static string ToolBar_Import {
            get {
                return ResourceManager.GetString("ToolBar_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 導入數據.
        /// </summary>
        internal static string ToolBar_ImportToolTip {
            get {
                return ResourceManager.GetString("ToolBar_ImportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        internal static string ToolBar_New {
            get {
                return ResourceManager.GetString("ToolBar_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增數據.
        /// </summary>
        internal static string ToolBar_NewToolTip {
            get {
                return ResourceManager.GetString("ToolBar_NewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查詢.
        /// </summary>
        internal static string ToolBar_Search {
            get {
                return ResourceManager.GetString("ToolBar_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查詢滿足條件的記錄.
        /// </summary>
        internal static string ToolBar_SearchToolTip {
            get {
                return ResourceManager.GetString("ToolBar_SearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允許的文件類型：.
        /// </summary>
        internal static string Uploader_AllowedContentTypes {
            get {
                return ResourceManager.GetString("Uploader_AllowedContentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要上傳的文件不存在.
        /// </summary>
        internal static string Uploader_FileDoesNotExistErrorText {
            get {
                return ResourceManager.GetString("Uploader_FileDoesNotExistErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件路徑.
        /// </summary>
        internal static string Uploader_FilePath {
            get {
                return ResourceManager.GetString("Uploader_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上傳時發生錯誤.
        /// </summary>
        internal static string Uploader_GeneralErrorText {
            get {
                return ResourceManager.GetString("Uploader_GeneralErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 導入向導.
        /// </summary>
        internal static string Uploader_Import {
            get {
                return ResourceManager.GetString("Uploader_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大文件大小：.
        /// </summary>
        internal static string Uploader_MaxFileSize {
            get {
                return ResourceManager.GetString("Uploader_MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上傳的文件超過了限制大小.
        /// </summary>
        internal static string Uploader_MaxFileSizeErrorText {
            get {
                return ResourceManager.GetString("Uploader_MaxFileSizeErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持的文件類型.
        /// </summary>
        internal static string Uploader_NotAllowedContentTypeErrorText {
            get {
                return ResourceManager.GetString("Uploader_NotAllowedContentTypeErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上傳模板.
        /// </summary>
        internal static string Uploader_Template {
            get {
                return ResourceManager.GetString("Uploader_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上傳.
        /// </summary>
        internal static string Uploader_Upload {
            get {
                return ResourceManager.GetString("Uploader_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 導入處理完成。.
        /// </summary>
        internal static string Uploader_UploadCompleted {
            get {
                return ResourceManager.GetString("Uploader_UploadCompleted", resourceCulture);
            }
        }
    }
}
