//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfy.App.Core.QualityCode
{


    [System.Serializable()]
    public class PbknitfinishModelList : Comfy.Data.DataObjectList<PbknitfinishModel>
    {
    }

    [System.Serializable()]
    public partial class PbknitfinishModel : Comfy.Data.DataObject<PbknitfinishModel>
    {

        #region Member Field Region
        private string _FinishingCode;

        private string _FinishingName;

        private string _Description;

        private string _WashingFlag;

        private string _IsActive;
        #endregion

        #region Member Property Region
        /// <summary>
        /// <para>整理方式ID</para>
        /// </summary>
        public string FinishingCode
        {
            get
            {
                return this._FinishingCode;
            }
            set
            {
                base.SetValue(ref this._FinishingCode, value);
            }
        }

        /// <summary>
        /// <para>英文描述</para>
        /// </summary>
        public string FinishingName
        {
            get
            {
                return this._FinishingName;
            }
            set
            {
                base.SetValue(ref this._FinishingName, value);
            }
        }

        /// <summary>
        /// <para>中文描述</para>
        /// </summary>
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                base.SetValue(ref this._Description, value);
            }
        }

        /// <summary>
        /// <para>是否成衣洗水</para>
        /// </summary>
        public string WashingFlag
        {
            get
            {
                return this._WashingFlag;
            }
            set
            {
                base.SetValue(ref this._WashingFlag, value);
            }
        }

        /// <summary>
        /// <para>是否有效</para>
        /// </summary>
        public string IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                base.SetValue(ref this._IsActive, value);
            }
        }
        #endregion
    }
}
