//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfy.App.Core.QualityCode
{
    using Comfy.Data;
    using Comfy.App.Core.QualityCode;


    public class PbknitparameterManager
    {

        public PbknitparameterModelList GetModelList(PbknitparameterModel model)
        {
            PbknitparameterTable table = new PbknitparameterTable();
            SelectSqlSection sql = DataAccess.DefaultDB.Select(table, table.AllColumns())
                ;
            using (SafeDataReader sdr = new SafeDataReader(sql.ToDataReader()))
            {
                PbknitparameterModelList result = new PbknitparameterModelList();
                while (sdr.Read())
                {
                    PbknitparameterModel m = new PbknitparameterModel();
                    m.Sort = sdr.GetString(table.Sort);
                    m.Parameter = sdr.GetString(table.Parameter);
                    m.IsActive = sdr.GetString(table.IsActive);
                    result.Add(m);
                }
                return result;
            }
        }

        public void AddModel(PbknitparameterModel model)
        {
            //model.CreateTime = System.DateTime.Now;
            PbknitparameterTable table = new PbknitparameterTable();
            DataAccess.DefaultDB.Insert(table)
                .AddColumn(table.Sort, model.Sort)
                .AddColumn(table.Parameter, model.Parameter)
                .AddColumn(table.IsActive, model.IsActive)
                .Execute();
        }

        public void UpdateModel(PbknitparameterModel model)
        {
            //model.UpdateTime = System.DateTime.Now;
            PbknitparameterTable table = new PbknitparameterTable();
            DataAccess.DefaultDB.Update(table)
                .AddColumn(table.Sort, model.Sort)
                .AddColumn(table.Parameter, model.Parameter)
                .AddColumn(table.IsActive, model.IsActive)
                .Execute();
        }

        public void DeleteModel(PbknitparameterModel model)
        {
            PbknitparameterTable table = new PbknitparameterTable();
            DataAccess.DefaultDB.Delete(table)
                .Execute();
        }

        protected bool Exists(PbknitparameterModel model, bool isNew)
        {
            PbknitparameterTable table = new PbknitparameterTable();
            SelectSqlSection sql = DataAccess.DefaultDB.Select(table, QueryColumn.All().Count())
                .Where(table.Sort == model.Sort
                && table.Parameter == model.Parameter
                && table.IsActive == model.IsActive
                );
            return sql.ToScalar<int>() > 0;
        }

        public void CheckModel(PbknitparameterModel model, bool isNew)
        {
            Validator v = new Validator();
            //Check model's data here.
            if (!v.IsValid)
                throw new ValidationException(v);
        }
    }
}
