//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfy.App.Core.QualityCode
{


    [System.Serializable()]
    public class PbknitparameterModelList : Comfy.Data.DataObjectList<PbknitparameterModel>
    {
    }

    [System.Serializable()]
    public partial class PbknitparameterModel : Comfy.Data.DataObject<PbknitparameterModel>
    {

        #region Member Field Region
        private string _Sort;

        private string _Parameter;

        private string _IsActive;
        #endregion

        #region Member Property Region
        /// <summary>
        /// <para>参数类型</para>
        /// </summary>
        public string Sort
        {
            get
            {
                return this._Sort;
            }
            set
            {
                base.SetValue(ref this._Sort, value);
            }
        }

        /// <summary>
        /// <para>参数值</para>
        /// </summary>
        public string Parameter
        {
            get
            {
                return this._Parameter;
            }
            set
            {
                base.SetValue(ref this._Parameter, value);
            }
        }

        /// <summary>
        /// <para>是否有效</para>
        /// </summary>
        public string IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                base.SetValue(ref this._IsActive, value);
            }
        }
        #endregion
    }
}
