//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfy.App.Core.QualityCode
{


    [System.Serializable()]
    public class PbknityarncountModelList : Comfy.Data.DataObjectList<PbknityarncountModel>
    {
    }

    [System.Serializable()]
    public partial class PbknityarncountModel : Comfy.Data.DataObject<PbknityarncountModel>
    {

        #region Member Field Region
        private string _YarnCount;

        private string _IsActive;
        #endregion

        #region Member Property Region
        /// <summary>
        /// <para>纱支</para>
        /// </summary>
        public string YarnCount
        {
            get
            {
                return this._YarnCount;
            }
            set
            {
                base.SetValue(ref this._YarnCount, value);
            }
        }

        /// <summary>
        /// <para>是否有效</para>
        /// </summary>
        public string IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                base.SetValue(ref this._IsActive, value);
            }
        }
        #endregion
    }
}
