//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfy.App.Core.QualityCode
{


    [System.Serializable()]
    public class PbknitdyemethodModelList : Comfy.Data.DataObjectList<PbknitdyemethodModel>
    {
    }

    [System.Serializable()]
    public partial class PbknitdyemethodModel : Comfy.Data.DataObject<PbknitdyemethodModel>
    {

        #region Member Field Region
        private string _DyeMethod;

        private string _DyeType;

        private string _Description;
        #endregion

        #region Member Property Region
        /// <summary>
        /// <para>染方式ID</para>
        /// </summary>
        public string DyeMethod
        {
            get
            {
                return this._DyeMethod;
            }
            set
            {
                base.SetValue(ref this._DyeMethod, value);
            }
        }

        /// <summary>
        /// <para>染方式类型</para>
        /// </summary>
        public string DyeType
        {
            get
            {
                return this._DyeType;
            }
            set
            {
                base.SetValue(ref this._DyeType, value);
            }
        }

        /// <summary>
        /// <para>染方式描述</para>
        /// </summary>
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                base.SetValue(ref this._Description, value);
            }
        }
        #endregion
    }
}
