//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfy.App.Core.QualityCode
{


    [System.Serializable()]
    public class QcavailablewidthModelList : Comfy.Data.DataObjectList<QcavailablewidthModel>
    {
    }

    [System.Serializable()]
    public partial class QcavailablewidthModel : Comfy.Data.DataObject<QcavailablewidthModel>
    {

        #region Member Field Region
        private int _Iden;

        private string _QualityCode;

        private int _Gauge;

        private int _Diameter;

        private int _TotalNeedles;

        private decimal _Width;

        private decimal _MaxWidth;

        private string _UpdatedBy;

        private System.DateTime _UpdatedTime;
        #endregion

        #region Member Property Region
        /// <summary>
        /// <para>自动增长号</para>
        /// </summary>
        public int Iden
        {
            get
            {
                return this._Iden;
            }
            set
            {
                base.SetValue(ref this._Iden, value);
            }
        }

        /// <summary>
        /// <para>Quality Code</para>
        /// </summary>
        public string QualityCode
        {
            get
            {
                return this._QualityCode;
            }
            set
            {
                base.SetValue(ref this._QualityCode, value);
            }
        }

        /// <summary>
        /// <para>针距</para>
        /// </summary>
        public int Gauge
        {
            get
            {
                return this._Gauge;
            }
            set
            {
                base.SetValue(ref this._Gauge, value);
            }
        }

        /// <summary>
        /// <para>针筒直径</para>
        /// </summary>
        public int Diameter
        {
            get
            {
                return this._Diameter;
            }
            set
            {
                base.SetValue(ref this._Diameter, value);
            }
        }

        /// <summary>
        /// <para>总针数</para>
        /// </summary>
        public int TotalNeedles
        {
            get
            {
                return this._TotalNeedles;
            }
            set
            {
                base.SetValue(ref this._TotalNeedles, value);
            }
        }

        /// <summary>
        /// <para>门幅</para>
        /// </summary>
        public decimal Width
        {
            get
            {
                return this._Width;
            }
            set
            {
                base.SetValue(ref this._Width, value);
            }
        }

        /// <summary>
        /// <para>最大门幅</para>
        /// </summary>
        public decimal MaxWidth
        {
            get
            {
                return this._MaxWidth;
            }
            set
            {
                base.SetValue(ref this._MaxWidth, value);
            }
        }

        /// <summary>
        /// <para>更新人</para>
        /// </summary>
        public string UpdatedBy
        {
            get
            {
                return this._UpdatedBy;
            }
            set
            {
                base.SetValue(ref this._UpdatedBy, value);
            }
        }

        /// <summary>
        /// <para>更新时间</para>
        /// </summary>
        public System.DateTime UpdatedTime
        {
            get
            {
                return this._UpdatedTime;
            }
            set
            {
                base.SetValue(ref this._UpdatedTime, value);
            }
        }
        #endregion
    }
}
