//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。

//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果

//     重新生成代码，这些更改将会丢失。

// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfy.App.Core.QualityCode
{


    [System.Serializable()]
    public class QccustomerlibraryModelList : Comfy.Data.DataObjectList<QccustomerlibraryModel>
    {
    }

    [System.Serializable()]
    public partial class QccustomerlibraryModel : Comfy.Data.DataObject<QccustomerlibraryModel>
    {

        #region Member Field Region
        private int _Iden;

        private string _QualityCode;

        private string _BuyerId;

        private string _Brand;

        private string _CustomerQualityId;

        private string _Sales;

        private string _SalesGroup;

        private string _MillComments;

        private string _IsFirstOwner;

        private System.DateTime _CreateDate;

        private string _Creator;

        public string Status { get; set; }

        public string BuyerName { get; set; }
        public string SalesName { get; set; }
        public string BuyerIdNew { get; set; }

        #endregion

        #region Member Property Region
        /// <summary>
        /// <para>自动增长号</para>
        /// </summary>
        public int Iden
        {
            get
            {
                return this._Iden;
            }
            set
            {
                base.SetValue(ref this._Iden, value);
            }
        }

        /// <summary>
        /// <para>Quality Code</para>
        /// </summary>
        public string QualityCode
        {
            get
            {
                return this._QualityCode;
            }
            set
            {
                base.SetValue(ref this._QualityCode, value);
            }
        }

        /// <summary>
        /// <para>eSCM客户ID</para>
        /// </summary>
        public string BuyerId
        {
            get
            {
                return this._BuyerId;
            }
            set
            {
                base.SetValue(ref this._BuyerId, value);
            }
        }

        /// <summary>
        /// <para>品牌</para>
        /// </summary>
        public string Brand
        {
            get
            {
                return this._Brand;
            }
            set
            {
                base.SetValue(ref this._Brand, value);
            }
        }

        /// <summary>
        /// <para>客户质量代码</para>
        /// </summary>
        public string CustomerQualityId
        {
            get
            {
                return this._CustomerQualityId;
            }
            set
            {
                base.SetValue(ref this._CustomerQualityId, value);
            }
        }

        /// <summary>
        /// <para>Sales ID</para>
        /// </summary>
        public string Sales
        {
            get
            {
                return this._Sales;
            }
            set
            {
                base.SetValue(ref this._Sales, value);
            }
        }

        /// <summary>
        /// <para>Sales组别</para>
        /// </summary>
        public string SalesGroup
        {
            get
            {
                return this._SalesGroup;
            }
            set
            {
                base.SetValue(ref this._SalesGroup, value);
            }
        }

        /// <summary>
        /// <para>工厂批注</para>
        /// </summary>
        public string MillComments
        {
            get
            {
                return this._MillComments;
            }
            set
            {
                base.SetValue(ref this._MillComments, value);
            }
        }

        /// <summary>
        /// <para>是否为最初创建客户</para>
        /// </summary>
        public string IsFirstOwner
        {
            get
            {
                return this._IsFirstOwner;
            }
            set
            {
                base.SetValue(ref this._IsFirstOwner, value);
            }
        }

        /// <summary>
        /// <para>创建日期</para>
        /// </summary>
        public System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                base.SetValue(ref this._CreateDate, value);
            }
        }

        /// <summary>
        /// <para>创建人</para>
        /// </summary>
        public string Creator
        {
            get
            {
                return this._Creator;
            }
            set
            {
                base.SetValue(ref this._Creator, value);
            }
        }
        #endregion
    }
}
