//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。

//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果

//     重新生成代码，这些更改将会丢失。

// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfy.App.Core.QualityCode
{


    [System.Serializable()]
    public class QcfinishdtlModelList : Comfy.Data.DataObjectList<QcfinishdtlModel>
    {
    }

    [System.Serializable()]
    public partial class QcfinishdtlModel : Comfy.Data.DataObject<QcfinishdtlModel>
    {

        #region Member Field Region
        private int _Iden;

        private string _QualityCode;

        private string _FinishingCode;

        
        #endregion

        #region Member Property Region
        /// <summary>
        /// <para>自动增长号</para>
        /// </summary>
        public int Iden
        {
            get
            {
                return this._Iden;
            }
            set
            {
                base.SetValue(ref this._Iden, value);
            }
        }

        /// <summary>
        /// <para>Quality Code</para>
        /// </summary>
        /// 
        public string Description { get; set; }
        public string QualityCode
        {
            get
            {
                return this._QualityCode;
            }
            set
            {
                base.SetValue(ref this._QualityCode, value);
            }
        }

        /// <summary>
        /// <para>整理方式ID</para>
        /// </summary>
        public string FinishingCode
        {
            get
            {
                return this._FinishingCode;
            }
            set
            {
                base.SetValue(ref this._FinishingCode, value);
            }
        }
        #endregion
    }
}
