//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfy.App.Core.QualityCode
{


    [System.Serializable()]
    public class QcmaininfologModelList : Comfy.Data.DataObjectList<QcmaininfologModel>
    {
    }

    [System.Serializable()]
    public partial class QcmaininfologModel : Comfy.Data.DataObject<QcmaininfologModel>
    {

        #region Member Field Region
        private string _QualityCode;

        private string _Status;

        private string _EditReason;

        private string _EditorContent;

        private string _Editor;

        private System.DateTime _EditorTime;
        #endregion

        #region Member Property Region
        /// <summary>
        /// <para></para>
        /// </summary>
        public string QualityCode
        {
            get
            {
                return this._QualityCode;
            }
            set
            {
                base.SetValue(ref this._QualityCode, value);
            }
        }

        /// <summary>
        /// <para></para>
        /// </summary>
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                base.SetValue(ref this._Status, value);
            }
        }

        /// <summary>
        /// <para></para>
        /// </summary>
        public string EditReason
        {
            get
            {
                return this._EditReason;
            }
            set
            {
                base.SetValue(ref this._EditReason, value);
            }
        }

        /// <summary>
        /// <para></para>
        /// </summary>
        public string EditorContent
        {
            get
            {
                return this._EditorContent;
            }
            set
            {
                base.SetValue(ref this._EditorContent, value);
            }
        }

        /// <summary>
        /// <para></para>
        /// </summary>
        public string Editor
        {
            get
            {
                return this._Editor;
            }
            set
            {
                base.SetValue(ref this._Editor, value);
            }
        }

        /// <summary>
        /// <para></para>
        /// </summary>
        public System.DateTime EditorTime
        {
            get
            {
                return this._EditorTime;
            }
            set
            {
                base.SetValue(ref this._EditorTime, value);
            }
        }
        #endregion
    }
}
