//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。

//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果

//     重新生成代码，这些更改将会丢失。

// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfy.App.Core.QualityCode
{


    [System.Serializable()]
    public class QcmaininfoModelList : Comfy.Data.DataObjectList<QcmaininfoModel>
    {
    }

    [System.Serializable()]
    public partial class QcmaininfoModel : Comfy.Data.DataObject<QcmaininfoModel>
    {

        #region Member Field Region


        public string QC_Key { get; set; }


        public int GridRowCount { get; set; }
        public string TempComments { get; set; }
        public string CustomerQualityId { get; set; }
        public string MillComments { get; set; }
        public string AvaWidth { get; set; }
        public string YarnInfo { get; set; }
        public string SpecialType { get; set; }
        private string _QualityCode;
        public string BuyserIds { get; set; }
        public string Brank { get; set; }
        public string ReplaceBy { get; set; }
        public string ApprovedFromSPPO { get; set; }

        //modify:gaofeng 2021 / 01 / 18 < 2021 - 0001 QC System Enhancement from sales > --begin

        public string ApprovedFromSPPO_Usage { get; set; }
        //modify:gaofeng 2021 / 01 / 18 < 2021 - 0001 QC System Enhancement from sales > --end



        //Add by Sunny 2017 0904
        public string CustomerComment { get; set; }

        private System.DateTime _CreateDate;

        private string _Creator;

        private System.DateTime _ApproveDate;

        private string _Approver;

        private string _Status;

        private string _Sourcing;

        private string _MaterialGroup;

        private string _AnalysisNo;

        private string _RefQualityCode;

        private string _Pattern;


        private string _Remark;
        private string _Riskrade;
        private string _DyeMethod;

        private int _BfGmmm;

        private int _AfGmmm;

        private string _Shrinkage;

        private string _ShrinkageTestingMethod;

        private string _GmtWashing;

        private string _Layout;

        private string _YarnLength;

        private string _TappingType;

        private string _Measurement;

        private System.DateTime _LastUpdateTime;

        public string Construction{get;set;}
        public string Finishing{get;set;}
        public string CustomerCode { get; set; }

        private string _LastUpdateBy;

        private string _GK_NO;

        private string _Repeat;

        public string GK_NO
        {
            get { return _GK_NO; }
            set { _GK_NO = value; }
        }



        private string _QC_Ref_PPO;

        public string QC_Ref_PPO
        {
            get { return _QC_Ref_PPO; }
            set { _QC_Ref_PPO = value; }
        }
        private string _QC_Ref_GP;

        public string QC_Ref_GP
        {
            get { return _QC_Ref_GP; }
            set { _QC_Ref_GP = value; }
        }
        private string _HF_Ref_PPO;

        public string HF_Ref_PPO
        {
            get { return _HF_Ref_PPO; }
            set { _HF_Ref_PPO = value; }
        }
        private string _HF_Ref_GP;

        public string HF_Ref_GP
        {
            get { return _HF_Ref_GP; }
            set { _HF_Ref_GP = value; }
        }

        private string _RF_Remark;

         public string RF_Remark
        {
            get { return _RF_Remark; }
            set { _RF_Remark = value; }
        }
        
       

        #endregion

        #region Member Property Region
        /// <summary>
        /// <para>Quality Code</para>
        /// </summary>
        public string QualityCode
        {
            get
            {
                return this._QualityCode;
            }
            set
            {
                base.SetValue(ref this._QualityCode, value);
            }
        }

        /// <summary>
        /// <para>创建日期</para>
        /// </summary>
        public System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                base.SetValue(ref this._CreateDate, value);
            }
        }

        /// <summary>
        /// <para>创建人</para>
        /// </summary>
        public string Creator
        {
            get
            {
                return this._Creator;
            }
            set
            {
                base.SetValue(ref this._Creator, value);
            }
        }


        /// <summary>
        /// <para>创建人</para>
        /// </summary>
        public string Remark
        {
            get
            {
                return this._Remark;
            }
            set
            {
                base.SetValue(ref this._Remark, value);
            }
        }

        public string Riskrade
        {

            get
            {
                return this._Riskrade;
            }
            set
            {
                base.SetValue(ref this._Riskrade, value);
            }
        }

        /// <summary>
        /// <para>确认日期</para>
        /// </summary>
        public System.DateTime ApproveDate
        {
            get
            {
                return this._ApproveDate;
            }
            set
            {
                base.SetValue(ref this._ApproveDate, value);
            }
        }

        /// <summary>
        /// <para>确认人</para>
        /// </summary>
        public string Approver
        {
            get
            {
                return this._Approver;
            }
            set
            {
                base.SetValue(ref this._Approver, value);
            }
        }

        /// <summary>
        /// <para>状态(New/Developed/Approved/Disabled)</para>
        /// </summary>
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                base.SetValue(ref this._Status, value);
            }
        }

        /// <summary>
        /// <para>来源(Internal/External)</para>
        /// </summary>
        public string Sourcing
        {
            get
            {
                return this._Sourcing;
            }
            set
            {
                base.SetValue(ref this._Sourcing, value);
            }
        }

        /// <summary>
        /// <para>物料类型(Fabric/Flat Knit Fabric/Tapping)</para>
        /// </summary>
        public string MaterialGroup
        {
            get
            {
                return this._MaterialGroup;
            }
            set
            {
                base.SetValue(ref this._MaterialGroup, value);
            }
        }

        /// <summary>
        /// <para>针织分析号</para>
        /// </summary>
        public string AnalysisNo
        {
            get
            {
                return this._AnalysisNo;
            }
            set
            {
                base.SetValue(ref this._AnalysisNo, value);
            }
        }

        /// <summary>
        /// <para>参考Quality Code</para>
        /// </summary>
        public string RefQualityCode
        {
            get
            {
                return this._RefQualityCode;
            }
            set
            {
                base.SetValue(ref this._RefQualityCode, value);
            }
        }

        /// <summary>
        /// <para>花型</para>
        /// </summary>
        public string Pattern
        {
            get
            {
                return this._Pattern;
            }
            set
            {
                base.SetValue(ref this._Pattern, value);
            }
        }

        /// <summary>
        /// <para>染方式ID</para>
        /// </summary>
        public string DyeMethod
        {
            get
            {
                return this._DyeMethod;
            }
            set
            {
                base.SetValue(ref this._DyeMethod, value);
            }
        }

        /// <summary>
        /// <para>洗前克重</para>
        /// </summary>
        public int BfGmmm
        {
            get
            {
                return this._BfGmmm;
            }
            set
            {
                base.SetValue(ref this._BfGmmm, value);
            }
        }

        /// <summary>
        /// <para>洗后克重</para>
        /// </summary>
        public int AfGmmm
        {
            get
            {
                return this._AfGmmm;
            }
            set
            {
                base.SetValue(ref this._AfGmmm, value);
            }
        }

        /// <summary>
        /// <para>缩水率</para>
        /// </summary>
        public string Shrinkage
        {
            get
            {
                return this._Shrinkage;
            }
            set
            {
                base.SetValue(ref this._Shrinkage, value);
            }
        }

        /// <summary>
        /// <para>缩率测试方法</para>
        /// </summary>
        public string ShrinkageTestingMethod
        {
            get
            {
                return this._ShrinkageTestingMethod;
            }
            set
            {
                base.SetValue(ref this._ShrinkageTestingMethod, value);
            }
        }

        /// <summary>
        /// <para>是否成衣洗水</para>
        /// </summary>
        public string GmtWashing
        {
            get
            {
                return this._GmtWashing;
            }
            set
            {
                base.SetValue(ref this._GmtWashing, value);
            }
        }

        /// <summary>
        /// <para>Layout</para>
        /// </summary>
        public string Layout
        {
            get
            {
                return this._Layout;
            }
            set
            {
                base.SetValue(ref this._Layout, value);
            }
        }

        /// <summary>
        /// <para>纱长</para>
        /// </summary>
        public string YarnLength
        {
            get
            {
                return this._YarnLength;
            }
            set
            {
                base.SetValue(ref this._YarnLength, value);
            }
        }

        /// <summary>
        /// <para>带子类型</para>
        /// </summary>
        public string TappingType
        {
            get
            {
                return this._TappingType;
            }
            set
            {
                base.SetValue(ref this._TappingType, value);
            }
        }

        /// <summary>
        /// <para>带子尺寸</para>
        /// </summary>
        public string Measurement
        {
            get
            {
                return this._Measurement;
            }
            set
            {
                base.SetValue(ref this._Measurement, value);
            }
        }

        /// <summary>
        /// <para>最后更新时间</para>
        /// </summary>
        public System.DateTime LastUpdateTime
        {
            get
            {
                return this._LastUpdateTime;
            }
            set
            {
                base.SetValue(ref this._LastUpdateTime, value);
            }
        }

        /// <summary>
        /// <para>最后更新人</para>
        /// </summary>
        public string LastUpdateBy
        {
            get
            {
                return this._LastUpdateBy;
            }
            set
            {
                base.SetValue(ref this._LastUpdateBy, value);
            }
        }

        /// <summary>
        /// <para>QC重复备注</para>
        /// </summary>
        public string Repeat
        {
            get
            {
                return this._Repeat;
            }
            set
            {
                //base.SetValue(ref this._Repeat, value);
                this._Repeat = value;
            }
        }
        #endregion
    }
}
