//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comfy.App.Core.QualityCode
{
    using Comfy.Data;
    using Comfy.App.Core.QualityCode;
    using System.Data.Common;


    public class QcyarndtlManager
    {

        public QcyarndtlModelList GetModelList(QcyarndtlModel model)
        {
            QcyarndtlTable table = new QcyarndtlTable();
            SelectSqlSection sql = DataAccess.DefaultDB.Select(table, table.AllColumns());
            if (model.QualityCode != "")
            {
                sql.Where(table.QualityCode == model.QualityCode);
            }
            using (SafeDataReader sdr = new SafeDataReader(sql.ToDataReader()))
            {
                QcyarndtlModelList result = new QcyarndtlModelList();
                while (sdr.Read())
                {
                    QcyarndtlModel m = new QcyarndtlModel();
                    m.Iden = sdr.GetInt32(table.Iden);
                    m.QualityCode = sdr.GetString(table.QualityCode);
                    m.YarnType = sdr.GetString(table.YarnType);
                    m.YarnCount = sdr.GetString(table.YarnCount);
                    m.Threads = sdr.GetInt32(table.Threads);
                    m.YarnRatio = sdr.GetDecimal(table.YarnRatio);
                    m.YarnComponent = sdr.GetString(table.YarnComponent);
                    m.WarpWeft = sdr.GetString(table.WarpWeft);
                    m.YarnDensity = sdr.GetInt32(table.YarnDensity);
                    result.Add(m);
                }
                return result;
            }
        }

        public void AddModel(QcyarndtlModel model, DbTransaction tran)
        {
            //model.CreateTime = System.DateTime.Now;
            QcyarndtlTable table = new QcyarndtlTable();
            InsertSqlSection insertSql = DataAccess.DefaultDB.Insert(table);
            if (tran != null)
            {
                insertSql.SetTransaction(tran);
            }
            int iden = DataAccess.DefaultDB.CustomSql("select QCYARNDTLIDEN.nextval from dual").ToScalar<int>();
            insertSql.AddColumn(table.QualityCode, model.QualityCode)
                .AddColumn(table.YarnType, model.YarnType)
                .AddColumn(table.YarnCount, model.YarnCount)
                .AddColumn(table.Threads, model.Threads)
                .AddColumn(table.YarnRatio, model.YarnRatio)
                .AddColumn(table.WarpWeft, model.WarpWeft)
                .AddColumn(table.YarnDensity, model.YarnDensity)
                .AddColumn(table.YarnComponent,model.YarnComponent)
                .AddColumn(table.Iden,iden)
                .Execute();
        }

        public void AddModels(QcyarndtlModelList models, DbTransaction tran)
        {
            for (int i = 0; i < models.Count; i++)
            {
                this.AddModel(models[i],tran);
            }
        }

        public void UpdateModel(QcyarndtlModel model, DbTransaction tran)
        {
            QcyarndtlTable table = new QcyarndtlTable();
            UpdateSqlSection sql = DataAccess.DefaultDB.Update(table);
            if (tran != null)
            {
                sql.SetTransaction(tran);
            }
            sql.AddColumn(table.YarnType, model.YarnType)
            .AddColumn(table.YarnCount, model.YarnCount)
            .AddColumn(table.Threads, model.Threads)
            .AddColumn(table.YarnRatio, model.YarnRatio)
            .AddColumn(table.YarnComponent,model.YarnComponent)
            .Where(table.QualityCode == model.QualityCode)
            .Execute();
        }

        public void DeleteModel(QcyarndtlModel model, DbTransaction tran)
        {
            QcyarndtlTable table = new QcyarndtlTable();
            DeleteSqlSection sql = DataAccess.DefaultDB.Delete(table);
            if (tran != null)
            {
                sql.SetTransaction(tran);
            }
            sql.Where(table.QualityCode == model.QualityCode)
                .Execute();
        }

        protected bool Exists(QcyarndtlModel model, bool isNew)
        {
            QcyarndtlTable table = new QcyarndtlTable();
            SelectSqlSection sql = DataAccess.DefaultDB.Select(table, QueryColumn.All().Count())
                .Where(table.Iden == model.Iden
                && table.QualityCode == model.QualityCode
                && table.YarnType == model.YarnType
                && table.YarnCount == model.YarnCount
                && table.Threads == model.Threads
                && table.YarnRatio == model.YarnRatio
                && table.WarpWeft == model.WarpWeft
                && table.YarnDensity == model.YarnDensity
                );
            return sql.ToScalar<int>() > 0;
        }

        public void CheckModel(QcyarndtlModel model, bool isNew)
        {
            Validator v = new Validator();
            //Check model's data here.
            if (!v.IsValid)
                throw new ValidationException(v);
        }
    }
}
